OPENINGS = [{'title': 'Сицилианская защита',
  'eco': 'B20',
  'popularity': 100,
  'player_color': 'black',
  'description': 'Самый популярный ответ чёрных. Асимметричная борьба с контратакой на флангах.',
  'pros': ['Неравный дисбаланс — сложнее готовиться белым',
           'Много острых вариантов с контратакой',
           'Хорошо подходит для борьбы за победу чёрными'],
  'cons': ['Требует глубокого знания теории',
           'Белые могут выбрать спокойный Anti-Sicilian',
           'Некоторые варианты очень затратны по времени'],
  'steps': [{'actor': 'bot', 'expected_move': 'e4', 'explanation': 'Белые занимают центр.'},
            {'actor': 'user', 'expected_move': 'c5', 'explanation': 'Сицилианская защита — атака на центр с фланга.'},
            {'actor': 'bot', 'expected_move': 'Nf3', 'explanation': 'Белые развивают коня и готовят d4.'},
            {'actor': 'user', 'expected_move': 'd6', 'explanation': 'Подготовка ...Nf6 и контроль e5.'},
            {'actor': 'bot', 'expected_move': 'd4', 'explanation': 'Белые разменивают в центре.'},
            {'actor': 'user', 'expected_move': 'cxd4', 'explanation': 'Размен в центре — классическая структура.'},
            {'actor': 'bot', 'expected_move': 'Nxd4', 'explanation': 'Конь возвращается в центр.'},
            {'actor': 'user', 'expected_move': 'Nf6', 'explanation': 'Развитие и давление на e4.'}]},
 {'title': 'Французская защита',
  'eco': 'C00',
  'popularity': 95,
  'player_color': 'black',
  'description': 'Прочная защита с контрударом в центре. Чёрные готовят стабильную структуру.',
  'pros': ['Прочная пешечная структура', 'Понятные планы: ...c5, ...Nc6, ...Bd6', 'Мало теории на базовом уровне'],
  'cons': ['Слон c8 часто пассивен', 'Пространство у белых в центре', 'Закрытые позиции могут быть тяжёлыми'],
  'steps': [{'actor': 'bot', 'expected_move': 'e4', 'explanation': 'Белые занимают центр.'},
            {'actor': 'user', 'expected_move': 'e6', 'explanation': 'Готовим ...d5, поддерживая центр.'},
            {'actor': 'bot', 'expected_move': 'd4', 'explanation': 'Белые строят большой центр.'},
            {'actor': 'user', 'expected_move': 'd5', 'explanation': 'Контрудар в центре — ключевая идея Французской.'},
            {'actor': 'bot', 'expected_move': 'Nc3', 'explanation': 'Белые защищают e4 и развиваются.'},
            {'actor': 'user', 'expected_move': 'Nf6', 'explanation': 'Развитие и давление на e4.'}]},
 {'title': 'Испанская партия',
  'eco': 'C60',
  'popularity': 92,
  'player_color': 'white',
  'description': 'Классический дебют. Белые давят на коня соперника и борются за центр.',
  'pros': ['Глубокая позиционная игра', 'Долговечный дебют на всех уровнях', 'Богатая теория и понятные планы'],
  'cons': ['Много теории в основных ветках', 'Берлинская защита упрощает игру', 'Медленное развитие атаки на старте'],
  'steps': [{'actor': 'user', 'expected_move': 'e4', 'explanation': 'Захват центра пешкой.'},
            {'actor': 'bot', 'expected_move': 'e5', 'explanation': 'Чёрные отвечают симметрично.'},
            {'actor': 'user', 'expected_move': 'Nf3', 'explanation': 'Развитие и атака на e5.'},
            {'actor': 'bot', 'expected_move': 'Nc6', 'explanation': 'Защита пешки e5.'},
            {'actor': 'user', 'expected_move': 'Bb5', 'explanation': 'Испанская партия — давление на коня c6.'}]},
 {'title': 'Итальянская партия',
  'eco': 'C50',
  'popularity': 88,
  'player_color': 'white',
  'description': 'Быстрая разработка фигур и давление на королевский фланг.',
  'pros': ['Простая и понятная схема развития', 'Быстрые атаки на короля в начале', 'Мало теории для старта'],
  'cons': ['После ...Bc5 позиция уравнивается',
           'Менее глубокий дебют, чем Испанская',
           'Чёрные имеют много равных вариантов'],
  'steps': [{'actor': 'user', 'expected_move': 'e4', 'explanation': 'Захват центра.'},
            {'actor': 'bot', 'expected_move': 'e5', 'explanation': 'Симметричный ответ.'},
            {'actor': 'user', 'expected_move': 'Nf3', 'explanation': 'Развитие коня.'},
            {'actor': 'bot', 'expected_move': 'Nc6', 'explanation': 'Защита e5.'},
            {'actor': 'user', 'expected_move': 'Bc4', 'explanation': 'Слон нацелен на слабое f7.'},
            {'actor': 'bot', 'expected_move': 'Bc5', 'explanation': 'Гармоничное развитие чёрных.'}]},
 {'title': 'Каро-Канн',
  'eco': 'B10',
  'popularity': 85,
  'player_color': 'black',
  'description': 'Надёжная защита с прочной пешечной структурой.',
  'pros': ['Очень прочная структура пешек', 'Мало теории на базовом уровне', 'Хорошо подходит для позиционной игры'],
  'cons': ['Меньше контратакующих шансов', 'Пространство у белых', 'Слон c8 требует активизации'],
  'steps': [{'actor': 'bot', 'expected_move': 'e4', 'explanation': 'Белые в центре.'},
            {'actor': 'user', 'expected_move': 'c6', 'explanation': 'Каро-Канн — подготовка ...d5.'},
            {'actor': 'bot', 'expected_move': 'd4', 'explanation': 'Большой центр белых.'},
            {'actor': 'user', 'expected_move': 'd5', 'explanation': 'Контрудар в центре.'},
            {'actor': 'bot', 'expected_move': 'Nc3', 'explanation': 'Защита e4.'},
            {'actor': 'user', 'expected_move': 'dxe4', 'explanation': 'Размен в центре.'},
            {'actor': 'bot', 'expected_move': 'Nxe4', 'explanation': 'Конь в центре.'},
            {'actor': 'user', 'expected_move': 'Nf6', 'explanation': 'Развитие с атакой на коня.'}]},
 {'title': 'Ферзевый гамбит',
  'eco': 'D06',
  'popularity': 82,
  'player_color': 'white',
  'description': 'Классический гамбит за преимущество в центре.',
  'pros': ['Простор в центре и на ферзевом фланге', 'Понятные позиционные планы', 'Популярен на всех уровнях'],
  'cons': ['Чёрные могут уравнять в Declined',
           'Требует знания пешечных структур',
           'Без точной игры преимущество уходит'],
  'steps': [{'actor': 'user', 'expected_move': 'd4', 'explanation': 'Захват центра.'},
            {'actor': 'bot', 'expected_move': 'd5', 'explanation': 'Чёрные в центре.'},
            {'actor': 'user', 'expected_move': 'c4', 'explanation': 'Ферзевый гамбит — давление на d5.'},
            {'actor': 'bot', 'expected_move': 'e6', 'explanation': 'Ферзевый гамбит отклонённый.'},
            {'actor': 'user', 'expected_move': 'Nc3', 'explanation': 'Развитие и давление на d5.'},
            {'actor': 'bot', 'expected_move': 'Nf6', 'explanation': 'Развитие чёрных.'}]},
 {'title': 'Лондонская система',
  'eco': 'D02',
  'popularity': 80,
  'player_color': 'white',
  'description': 'Универсальная система с минимумом теории и стабильной игрой.',
  'pros': ['Одна схема против многих ответов', 'Минимум теории', 'Прочная и понятная структура'],
  'cons': ['Меньше давления на старте', 'Легко уравнять чёрным', 'Менее амбициозно, чем 1.e4'],
  'steps': [{'actor': 'user', 'expected_move': 'd4', 'explanation': 'Захват центра.'},
            {'actor': 'bot', 'expected_move': 'd5', 'explanation': 'Симметричный ответ.'},
            {'actor': 'user', 'expected_move': 'Bf4', 'explanation': 'Слон до e2 — ключ Лондона.'},
            {'actor': 'bot', 'expected_move': 'Nf6', 'explanation': 'Развитие.'},
            {'actor': 'user', 'expected_move': 'e3', 'explanation': 'Поддержка d4 и место для слона.'},
            {'actor': 'bot', 'expected_move': 'e6', 'explanation': 'Прочная структура.'},
            {'actor': 'user', 'expected_move': 'Nf3', 'explanation': 'Завершение развития.'}]},
 {'title': 'Скандинавская защита',
  'eco': 'B01',
  'popularity': 75,
  'player_color': 'black',
  'description': 'Немедленный контрудар в центре с ранним выходом ферзя.',
  'pros': ['Простая идея — сразу атаковать e4', 'Выводит из книги неподготовленных', 'Быстрое развитие фигур'],
  'cons': ['Ранний выход ферзя может быть опасен', 'Белые получают темп развития', 'Теория в пользу белых'],
  'steps': [{'actor': 'bot', 'expected_move': 'e4', 'explanation': 'Белые в центре.'},
            {'actor': 'user', 'expected_move': 'd5', 'explanation': 'Скандинавская — сразу атакуем e4.'},
            {'actor': 'bot', 'expected_move': 'exd5', 'explanation': 'Белые принимают.'},
            {'actor': 'user', 'expected_move': 'Qxd5', 'explanation': 'Ферзь восстанавливает материал.'},
            {'actor': 'bot', 'expected_move': 'Nc3', 'explanation': 'Темп на ферзя.'},
            {'actor': 'user', 'expected_move': 'Qa5', 'explanation': 'Ферзь в безопасности на a5.'}]},
 {'title': 'Защита Алехина',
  'eco': 'B02',
  'popularity': 72,
  'player_color': 'black',
  'description': 'Провокационная защита: чёрные провоцируют белых расширять центр.',
  'pros': ['Провоцирует переэкспансию белых', 'Нестандартные позиции', 'Хорошо для практики контратаки'],
  'cons': ['Белые получают пространство', 'Требует точного тактического зрения', 'Мало популярен на высоком уровне'],
  'steps': [{'actor': 'bot', 'expected_move': 'e4', 'explanation': 'Белые в центре.'},
            {'actor': 'user', 'expected_move': 'Nf6', 'explanation': 'Алехин — атака на e4 конём.'},
            {'actor': 'bot', 'expected_move': 'e5', 'explanation': 'Белые гонят коня.'},
            {'actor': 'user', 'expected_move': 'Nd5', 'explanation': 'Конь отступает в центр.'},
            {'actor': 'bot', 'expected_move': 'd4', 'explanation': 'Большой центр.'},
            {'actor': 'user', 'expected_move': 'd6', 'explanation': 'Подрыв центра и развитие.'}]},
 {'title': 'Английское начало',
  'eco': 'A10',
  'popularity': 70,
  'player_color': 'white',
  'description': 'Фланговый контроль центра и гибкие транспозиции.',
  'pros': ['Гибкость и транспозиции', 'Меньше прямой теории', 'Контроль центра с фланга'],
  'cons': ['Медленнее, чем 1.e4 или 1.d4', 'Сложнее для начинающих', 'Чёрные имеют много равных ответов'],
  'steps': [{'actor': 'user', 'expected_move': 'c4', 'explanation': 'Английское — контроль d5 с фланга.'},
            {'actor': 'bot', 'expected_move': 'e5', 'explanation': 'Симметричный захват центра.'},
            {'actor': 'user', 'expected_move': 'Nc3', 'explanation': 'Развитие и контроль d5.'},
            {'actor': 'bot', 'expected_move': 'Nf6', 'explanation': 'Развитие.'},
            {'actor': 'user', 'expected_move': 'g3', 'explanation': 'Готовим фианкето слона.'}]},
 {'title': 'Защита Петрова',
  'eco': 'C42',
  'popularity': 68,
  'player_color': 'black',
  'description': 'Симметричная и солидная защита против королевского пешечного начала.',
  'pros': ['Солидная и равная игра', 'Мало теории на базовом уровне', 'Хорошо против 1.e4'],
  'cons': ['Часто упрощения и ничьи', 'Меньше шансов на победу', 'Белые могут выбрать острые ветки'],
  'steps': [{'actor': 'bot', 'expected_move': 'e4', 'explanation': 'Белые в центре.'},
            {'actor': 'user', 'expected_move': 'e5', 'explanation': 'Симметричный ответ.'},
            {'actor': 'bot', 'expected_move': 'Nf3', 'explanation': 'Развитие.'},
            {'actor': 'user', 'expected_move': 'Nf6', 'explanation': 'Петров — атака на e4.'},
            {'actor': 'bot', 'expected_move': 'Nxe5', 'explanation': 'Белые берут пешку.'},
            {'actor': 'user', 'expected_move': 'd6', 'explanation': 'Возвращаем темп и развиваемся.'}]},
 {'title': 'Славянская защита',
  'eco': 'D10',
  'popularity': 65,
  'player_color': 'black',
  'description': 'Прочная защита центра без блокировки слона.',
  'pros': ['Прочная структура без слабостей', 'Слон c8 не заблокирован', 'Популярна на всех уровнях'],
  'cons': ['Пассивные позиции без точных планов', 'Белые пространство в центре', 'Сложно играть на победу'],
  'steps': [{'actor': 'bot', 'expected_move': 'd4', 'explanation': 'Белые в центре.'},
            {'actor': 'user', 'expected_move': 'd5', 'explanation': 'Захват центра.'},
            {'actor': 'bot', 'expected_move': 'c4', 'explanation': 'Ферзевый гамбит.'},
            {'actor': 'user', 'expected_move': 'c6', 'explanation': 'Славянская — поддержка d5.'},
            {'actor': 'bot', 'expected_move': 'Nf3', 'explanation': 'Развитие.'},
            {'actor': 'user', 'expected_move': 'Nf6', 'explanation': 'Развитие коня.'},
            {'actor': 'bot', 'expected_move': 'Nc3', 'explanation': 'Белые развиваются.'},
            {'actor': 'user', 'expected_move': 'e6', 'explanation': 'Завершение развития.'}]},
 {'title': 'Королевский индианский',
  'eco': 'E60',
  'popularity': 62,
  'player_color': 'black',
  'description': 'Гибкая защита с фианкето и контратакой на королевском фланге.',
  'pros': ['Гибкая структура', 'Контратака на королевском фланге', 'Богатые позиционные идеи'],
  'cons': ['Пассивный старт', 'Белые пространство и инициатива', 'Требует понимания планов'],
  'steps': [{'actor': 'bot', 'expected_move': 'd4', 'explanation': 'Белые в центре.'},
            {'actor': 'user', 'expected_move': 'Nf6', 'explanation': 'Гибкий ответ.'},
            {'actor': 'bot', 'expected_move': 'c4', 'explanation': 'Простор в центре.'},
            {'actor': 'user', 'expected_move': 'g6', 'explanation': 'КИД — готовим фианкето.'},
            {'actor': 'bot', 'expected_move': 'Nc3', 'explanation': 'Развитие.'},
            {'actor': 'user', 'expected_move': 'Bg7', 'explanation': 'Слон на длинной диагонали.'}]},
 {'title': 'Шотландская партия',
  'eco': 'C45',
  'popularity': 58,
  'player_color': 'white',
  'description': 'Открытая игра с ранним разменом в центре.',
  'pros': ['Открытые позиции и тактика', 'Простая идея — d4', 'Хорошо для тренировки расчёта'],
  'cons': ['Много теории после 3...exd4', 'Чёрные быстро развиваются', 'Меньше позиционного давления'],
  'steps': [{'actor': 'user', 'expected_move': 'e4', 'explanation': 'Центр.'},
            {'actor': 'bot', 'expected_move': 'e5', 'explanation': 'Симметрия.'},
            {'actor': 'user', 'expected_move': 'Nf3', 'explanation': 'Развитие.'},
            {'actor': 'bot', 'expected_move': 'Nc6', 'explanation': 'Защита e5.'},
            {'actor': 'user', 'expected_move': 'd4', 'explanation': 'Шотландская — размен в центре.'},
            {'actor': 'bot', 'expected_move': 'exd4', 'explanation': 'Размен.'},
            {'actor': 'user', 'expected_move': 'Nxd4', 'explanation': 'Конь в центре.'}]},
 {'title': 'Венская партия',
  'eco': 'C25',
  'popularity': 55,
  'player_color': 'white',
  'description': 'Быстрое развитие с возможностью острой или спокойной игры.',
  'pros': ['Необычная схема — соперник может ошибиться', 'Быстрое развитие фигур', 'Гибкость планов'],
  'cons': ['Конь c3 блокирует c-пешку', 'Менее популярен на высоком уровне', 'Чёрные имеют проверенные ответы'],
  'steps': [{'actor': 'user', 'expected_move': 'e4', 'explanation': 'Центр.'},
            {'actor': 'bot', 'expected_move': 'e5', 'explanation': 'Симметрия.'},
            {'actor': 'user', 'expected_move': 'Nc3', 'explanation': 'Венская — ранний Nc3.'},
            {'actor': 'bot', 'expected_move': 'Nf6', 'explanation': 'Развитие.'},
            {'actor': 'user', 'expected_move': 'f4', 'explanation': 'Венский гамбит — атака на центр.'}]}]
